# Generated by Django 5.2.1 on 2026-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
    ]
