# Generated by Django 5.2.1 on 2026-05-05 17:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistedPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('quoted', 'Cotizado'), ('approved', 'Aprobado'), ('paid', 'Pagado'), ('purchased', 'Comprado'), ('received', 'Recibido'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='requested', max_length=20)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exchange_rate_real', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('exchange_rate_store', models.DecimalField(decimal_places=2, default=Decimal('1150.00'), max_digits=12)),
                ('customs_clp', models.PositiveIntegerField(default=0)),
                ('handling_clp', models.PositiveIntegerField(default=0)),
                ('other_costs_clp', models.PositiveIntegerField(default=0)),
                ('service_fee_clp', models.PositiveIntegerField(default=0)),
                ('total_customer_clp', models.PositiveIntegerField(default=0)),
                ('total_real_cost_clp', models.PositiveIntegerField(default=0)),
                ('profit_clp', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assisted_orders', to='products.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistedPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('external_sku', models.CharField(blank=True, max_length=120)),
                ('requested_condition', models.CharField(blank=True, max_length=20)),
                ('requested_language', models.CharField(blank=True, max_length=20)),
                ('is_foil', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assisted_order_items', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.assistedpurchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('subtotal_clp', models.PositiveIntegerField(default=0)),
                ('shipping_clp', models.PositiveIntegerField(default=0)),
                ('discount_clp', models.PositiveIntegerField(default=0)),
                ('total_clp', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_name_snapshot', models.CharField(default='', max_length=255)),
                ('product_type_snapshot', models.CharField(default='', max_length=20)),
                ('unit_price_clp', models.PositiveIntegerField(default=0)),
                ('subtotal_clp', models.PositiveIntegerField(default=0)),
                ('unit_cost_clp', models.IntegerField(default=0)),
                ('total_cost_clp', models.IntegerField(default=0)),
                ('gross_profit_clp', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
        ),
    ]
