# Generated by Django 5.2.1 on 2026-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistedpurchaseitem',
            options={'verbose_name': 'Producto de compra asistida', 'verbose_name_plural': 'Productos de compra asistida'},
        ),
        migrations.AlterModelOptions(
            name='assistedpurchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compra asistida', 'verbose_name_plural': 'Compras asistidas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Producto de orden', 'verbose_name_plural': 'Productos de orden'},
        ),
        migrations.AddField(
            model_name='order',
            name='stock_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assistedpurchaseorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('quoted', 'Cotizado'), ('approved', 'Aprobado'), ('paid', 'Pagado'), ('purchased', 'Comprado'), ('received', 'Recibido'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20),
        ),
    ]
