# Generated by Django 5.2.7 on 2026-05-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user_status_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_02a211_idx',
            old_name='orders_orde_user_id_f154a0_idx',
        ),
    ]
