# Generated by Django 5.2.1 on 2026-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundleitem',
            options={'verbose_name': 'Producto de bundle', 'verbose_name_plural': 'Productos de bundle'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='exchangerateconfig',
            options={'verbose_name': 'Configuración de dólar', 'verbose_name_plural': 'Configuraciones de dólar'},
        ),
        migrations.AlterModelOptions(
            name='inventorylot',
            options={'ordering': ['received_at', 'id'], 'verbose_name': 'Lote de inventario', 'verbose_name_plural': 'Lotes de inventario'},
        ),
        migrations.AlterModelOptions(
            name='kardexmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Movimiento Kardex', 'verbose_name_plural': 'Movimientos Kardex'},
        ),
        migrations.AlterModelOptions(
            name='mtgcard',
            options={'ordering': ['name', 'set_code', 'collector_number'], 'verbose_name': 'Carta MTG', 'verbose_name_plural': 'Cartas MTG'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'Producto de orden de compra', 'verbose_name_plural': 'Productos de orden de compra'},
        ),
        migrations.AlterModelOptions(
            name='sealedproduct',
            options={'verbose_name': 'Producto sellado', 'verbose_name_plural': 'Productos sellados'},
        ),
        migrations.AlterModelOptions(
            name='servicefeeconfig',
            options={'verbose_name': 'Configuración de comisión', 'verbose_name_plural': 'Configuraciones de comisión'},
        ),
        migrations.AlterModelOptions(
            name='shippingconfig',
            options={'verbose_name': 'Configuración de envío', 'verbose_name_plural': 'Configuraciones de envío'},
        ),
        migrations.AlterModelOptions(
            name='singlecard',
            options={'verbose_name': 'Carta individual', 'verbose_name_plural': 'Cartas individuales'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterUniqueTogether(
            name='bundleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='mtgcard',
            index=models.Index(fields=['name'], name='products_mt_name_4d56b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mtgcard',
            index=models.Index(fields=['set_code', 'collector_number'], name='products_mt_set_cod_f06705_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_pr_product_a5a1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'item'), name='unique_item_per_bundle'),
        ),
    ]
